CREATE TABLE IF NOT EXISTS squadre (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     nomesquadra varchar(64) NOT NULL,
                                     sport varchar(64) NOT NULL
);
CREATE TABLE IF NOT EXISTS partite (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    giorno varchar(64) NOT NULL,
    id_squdracasa varchar(64) NOT NULL,
    id_squadrafuori varchar(64) NOT NULL,
    sport varchar(64) NOT NULL,
    risultato varchar(64) NOT NULL);

insert into squadre (nomesquadra, sport)
    SELECT * FROM (
        values('peppina','polo'),
            ('gioia','lacrosse'),
            ('pollo','fune')
        ) as squadrep(nomesquadra, sport)
WHERE NOT EXISTS(SELECT 1 FROM squadre LIMIT 1);